Controllers/PostsController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Elixir.Models;
using X.PagedList;


namespace Elixir.Controllers
{
    public class PostsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PostsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Posts
        // GET: Posts
        public async Task<IActionResult> Index()
        {
            var posts = _context.Posts.Where(p => p.Status == true).ToList();
            return View(posts);
           
        }


        public IActionResult Search(string searchTerm)
        {
            var posts = _context.Posts.AsQueryable();

            if (!string.IsNullOrEmpty(searchTerm))
            {
                posts = posts.Where(p => p.Title.Contains(searchTerm) || p.ShortContent.Contains(searchTerm) || p.Content.Contains(searchTerm));
                ViewData["searchQuery"] = searchTerm;
            }
            else
            {
                // Nếu không có từ khóa tìm kiếm, trả về trang Index với toàn bộ danh sách bài viết
                return RedirectToAction(nameof(Index));
            }

            return View("Index", posts.ToList());
        }


        // GET: Posts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = await _context.Posts
                .FirstOrDefaultAsync(m => m.Id == id);
            if (post == null)
            {
                return NotFound();
            }

            return View(post);
        }

        // GET: Posts/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Posts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,ShortContent,Content,PostImage,Author,DateCreate,Status")] Post post)
        {
            if (ModelState.IsValid)
            {
                _context.Add(post);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(post);
        }

        // GET: Posts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = await _context.Posts.FindAsync(id);
            if (post == null)
            {
                return NotFound();
            }
            return View(post);
        }

        // POST: Posts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,ShortContent,Content,PostImage,Author,DateCreate,Status")] Post post)
        {
            if (id != post.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(post); 
                    _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PostExists(post.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(post);
        }

        // GET: Posts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = await _context.Posts
                .FirstOrDefaultAsync(m => m.Id == id);
            if (post == null)
            {
                return NotFound();
            }

            return View(post);
        }

        // POST: Posts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var post = await _context.Posts.FindAsync(id);
            if (post != null)
            {
                _context.Posts.Remove(post);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PostExists(int id)
        {
            return _context.Posts.Any(e => e.Id == id);
        }
    }
}

Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Elixir.Models;

namespace Elixir.Controllers
{
    public class ProductsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ProductsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Products
        public async Task<IActionResult> Index()
        {
            var product = _context.Products.Where(p => p.Status == true).ToList();
            return View(product);
        }

        // GET: Products/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .Include(p => p.Category)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }
        
    }
}

Views/Shared/_CopyrightPartialView.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<div class="container-fluid copyright py-4">
    <div class="container">
        <div class="row">
            <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                &copy; <a class="fw-medium" href="#">Elixirs</a>
            </div>
            <div class="col-md-6 text-center text-md-end">
                <!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->
                Designed By Winx
            </div>
        </div>
    </div>
</div>

Views/Shared/_FooterPartialView.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<div class="container-fluid bg-dark footer mt-5 py-5 wow fadeIn" data-wow-delay="0.1s">
    <div class="container py-5">
        <div class="row g-5">
            <div class="col-lg-3 col-md-6">
                <h4 class="text-primary mb-4">Địa chỉ</h4>
                <p class="mb-2"><i class="fa fa-map-marker-alt text-primary me-3"></i>78 Bế Văn Đàn, Đà Lạt, Lâm Đồng</p>
                <p class="mb-2"><i class="fa fa-phone-alt text-primary me-3"></i>+84914087809</p>
                <p class="mb-2"><i class="fa fa-envelope text-primary me-3"></i>hoangngocmanh2003@gmail.com</p>
                <div class="d-flex pt-3">
                    <a class="btn btn-square btn-primary rounded-circle me-2" href=""><i class="fab fa-twitter"></i></a>
                    <a class="btn btn-square btn-primary rounded-circle me-2" href=""><i class="fab fa-facebook-f"></i></a>
                    <a class="btn btn-square btn-primary rounded-circle me-2" href=""><i class="fab fa-youtube"></i></a>
                    <a class="btn btn-square btn-primary rounded-circle me-2" href=""><i class="fab fa-linkedin-in"></i></a>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <h4 class="text-primary mb-4">Lối tắt</h4>
                <a class="btn btn-link" href="">About Us</a>
                <a class="btn btn-link" href="">Contact Us</a>
                <a class="btn btn-link" href="">Support</a>
            </div>
            <div class="col-lg-3 col-md-6">
                <h4 class="text-primary mb-4">Giờ làm việc</h4>
                <p class="mb-1">Thứ 2 - Thứ 6</p>
                <h6 class="text-light">9:00 - 16:00</h6>
                <p class="mb-1">Thứ 7</p>
                <h6 class="text-light">09:00 - 12:00</h6>
                <p class="mb-1">Chủ nhật</p>
                <h6 class="text-light">Đóng cửa</h6>
            </div>
        </div>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Elixir - HerbalShop</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="~/HomeAssets/img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&family=Playfair+Display:wght@700;900&display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="~/HomeAssets/lib/animate/animate.min.css" rel="stylesheet">
    <link href="~/HomeAssets/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="~/HomeAssets/css/bootstrap.min.css" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="~/HomeAssets/css/style.css" rel="stylesheet">
    <style>
        .text-yellow {
            color: #FFD700 !important;
        }

        .logo {
            width: 100px;
            height: auto;
        }
    </style>

</head>

<body>
    <!-- Spinner Start -->
    <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
        <div class="spinner-border text-primary" role="status" style="width: 3rem; height: 3rem;"></div>
    </div>
    <!-- Spinner End -->
    <!-- Navbar Start -->
    @await Html.PartialAsync("_NavBarPartialView")
    <!-- Navbar End -->
    <!-- Carousel Start -->
    <div class="container-fluid px-0 mb-5">
        <div id="header-carousel" class="carousel slide carousel-fade" data-bs-ride="carousel">
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img class="w-100" src="~/HomeAssets/img/carousel-1.jpg" alt="Image">
                    <div class="carousel-caption">
                        <div class="container">
                            <div class="row justify-content-center">
                                <div class="col-lg-7 text-center">
                                    <p class="fs-4 text-white animated zoomIn">Chào mừng đến với <strong class="text-dark">Elixir</strong></p>
                                    <h4 class="display-1 text-dark mb-4 animated zoomIn">Khám phá thiên nhiên, chạm tới sức khỏe</h4>
                                    <a href="" class="btn btn-light rounded-pill py-3 px-5 animated zoomIn">Tìm hiểu thêm</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="carousel-item">
                    <img class="w-100" src="~/HomeAssets/img/carousel-2.jpg" alt="Image">
                    <div class="carousel-caption">
                        <div class="container">
                            <div class="row justify-content-center">
                                <div class="col-lg-7 text-center">
                                    <p class="fs-4 text-white animated zoomIn">Chào mừng đến với <strong class="text-dark">Elixir</strong></p>
                                    <h4 class="display-1 text-dark mb-4 animated zoomIn">Thảo dược tinh hoa, cuộc sống thịnh vượng</h4>
                                    <a href="" class="btn btn-light rounded-pill py-3 px-5 animated zoomIn">Tìm hiểu thêm</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#header-carousel"
                    data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#header-carousel"
                    data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
            </button>
        </div>
    </div>
    <!-- Carousel End -->
    @RenderBody()




    <!-- Footer Start -->
    @await Html.PartialAsync("_FooterPartialView")
    <!-- Footer End -->
    <!-- Copyright Start -->
    @await Html.PartialAsync("_CopyrightPartialView")
    <!-- Copyright End -->
    <!-- Back to Top -->
    <a href="#" class="btn btn-lg btn-primary btn-lg-square rounded-circle back-to-top"><i class="bi bi-arrow-up"></i></a>


    <!-- JavaScript Libraries -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/HomeAssets/lib/wow/wow.min.js"></script>
    <script src="~/HomeAssets/lib/easing/easing.min.js"></script>
    <script src="~/HomeAssets/lib/waypoints/waypoints.min.js"></script>
    <script src="~/HomeAssets/lib/owlcarousel/owl.carousel.min.js"></script>

    <!-- Template Javascript -->
    <script src="~/HomeAssets/js/main.js"></script>

    @RenderSection("Scripts", required: false)

</body>

</html>

Views/Shared/_NavBarPartialView.cshtml
<div class="container-fluid" style="background-color: #1A2926;">
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light py-2 py-lg-0">
            <a href="index.html" class="navbar-brand">
                <img class="img-fluid" src="~/HomeAssets/img/logodesign2.jpg" alt="Logo" style="width: 120px; height: auto;"> <!-- Tăng width lên 120px -->
            </a>
            <button type="button" class="navbar-toggler ms-auto me-0" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <div class="navbar-nav ms-auto">
                    <a class="nav-item nav-link text-yellow" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    <a class="nav-item nav-link text-yellow" asp-area="" asp-controller="Home" asp-action="About">About Us</a>
                    <a class="nav-item nav-link text-yellow" asp-area="" asp-controller="Products" asp-action="Index">Store</a>
                    <a class="nav-item nav-link text-yellow" asp-area="" asp-controller="Home" asp-action="Contact">Contact</a>
                    <a class="nav-item nav-link text-yellow" asp-area="" asp-controller="Posts" asp-action="Index">Blog</a>
                    <partial name="_LoginPartial" />
                </div>
                <div class="border-start ps-4 d-none d-lg-block">
                </div>
                <form class="d-flex">
                    <button class="btn btn-outline-dark text-yellow" type="submit">
                        <i class="bi-cart-fill me-1"></i>

                    </button>
                </form>
            </div>
        </nav>
    </div>
</div>